[tool.black]
line-length = 88
target-version = ["py37"]

[tool.isort]
profile = "black"
lines_after_imports = 2

[tool.mypy]
files = ["colandr/**/*.py"]
python_version = "3.7"
pretty = true
ignore_errors = true
allow_redefinition = true
ignore_missing_imports = true
follow_imports = "silent"

[tool.pytest.ini_options]
addopts = "--verbose"
testpaths = ["tests"]

[tool.ruff]
select = [
  "E",  # pycodestyle rules
  "F",  # pyflakes rules
]
ignore = ["E501"]
line-length = 88
target-version = "py37"
src = ["colandr"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]  # ignore unused imports in `__init__.py` files
