apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/colandr-back: "true"
        io.kompose.service: broker
    spec:
      containers:
        - image: redis:7.0
          livenessProbe:
            exec:
              command:
                - redis-cli ping
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: colandr-broker
          ports:
            - containerPort: 6379
              hostPort: 6379
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: broker-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
      volumes:
        - name: broker-data
          persistentVolumeClaim:
            claimName: broker-data
