apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: broker-data
  name: broker-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
