apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: colandr-worker
  name: colandr-worker
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: colandr-worker
