apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: email
  name: email
spec:
  ports:
    - name: "8025"
      port: 8025
      targetPort: 8025
    - name: "1025"
      port: 1025
      targetPort: 1025
  selector:
    io.kompose.service: email
