name: checks

on:
  push:
    branches: [ main, develop ]
  pull_request:  # run on all PRs
  schedule:  # run weekly
    - cron: "0 12 * * 0"

# HACK: let's add fake colandr envvars so tests can run
# TODO (burton): figure out a better way of configuring the app!
env:
  COLANDR_SECRET_KEY: "colandr_secret_key"
  COLANDR_PASSWORD_SALT: "colandr_password_salt"
  COLANDR_APP_DIR: "/path/to/colandr"
  COLANDR_MAIL_USERNAME: "colandr_mail_username"
  COLANDR_MAIL_PASSWORD: "colandr_mail_password"
  COLANDR_DATABASE_URI: "postgresql://colandr_app:password@localhost:5432/colandr"

jobs:

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8",]
        # TODO: also run on macos-latest pending docker/colima issue
        os: [ubuntu-latest]

    services:
      # NOTE: these containers should match those in app's docker compose file
      colandr_db:
        image: "postgres:14"
        env:
          POSTGRES_USER: "colandr_app"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "colandr"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      colandr_broker:
        image: "redis:6.0"
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e '.[dev]'
    - name: Download language data
      run: |
        python3 -m textacy download lang_identifier
        python3 -m spacy download en_core_web_md
    - name: Test with pytest
      run: |
        python -m pytest tests --verbose
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e '.[dev]'
    - name: Check formatting with black
      run: |
        python -m black --check --diff --verbose colandr
    - name: Check imports with isort
      run: |
        python -m isort --check --diff --verbose colandr
    - name: Check correctness with ruff
      run: |
        python -m ruff check --exit-zero colandr
  types:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "pip"
        cache-dependency-path: "pyproject.toml"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -e '.[dev]'
    - name: Check types with mypy
      run: |
        python -m mypy --install-types --non-interactive colandr
